### ISSUE TITLE
Replace deislabs entry with cnabio/community entry?

### ISSUE THREAD

**Issue by vdice** [cnabio/cnab.io#25]
While updating URLs per the move to the `cnabio` org, I noticed the deislabs entry in https://github.com/cnabio/cnab.io/blob/master/themes/cnab/layouts/partials/footer.html#L7

Perhaps we should replace with a cnabio entry?  Maybe https://github.com/cnabio/community ?

cc @carolynvs @flynnduism

**Comment by carolynvs** [comment]
I'm not sure, other than it shouldn't be deislabs anymore. I'll leave it up to Ronan.

**Comment by technosophos** [comment]
We should remove the DeisLabs logo and verbage from the bottom of cnab.io and duffle.sh
