### ISSUE TITLE
Remove example bundles entry

### ISSUE THREAD

**Issue by vdice** [cnabio/cnab.io#26]
The link to a former example bundles repository that is slated for deprecation should be replaced or removed: https://github.com/cnabio/cnab.io/blob/master/themes/cnab/layouts/index.html#L96-L107

I believe https://github.com/cnabio/duffle/pull/877 started the work to migrate a subset to the duffle repo.

And/or add a link to some [Porter](https://porter.sh/) example bundles?

cc @flynnduism @carolynvs

**Comment by carolynvs** [comment]
The porter example bundles don't show the cnab bundle, since we don't check that in. So I don't think that would work well here as a replacement.
