### ISSUE TITLE
Footer nav sometimes broken

### ISSUE THREAD

**Issue by vdice** [cnabio/cnab.io#34]
It looks like the footer navigation bar is malformed on certain pages besides the main https://cnab.io page.  This happens to me while viewing via a desktop web browser (Chrome, Edge).

Check out https://cnab.io/community-projects/ for example:

![Screen Shot 2020-03-13 at 12 22 01 PM](https://user-images.githubusercontent.com/9322017/76653147-5efc2680-6525-11ea-8ce3-b9ade41a0d9d.png)

**Comment by carolynvs** [comment]
Closing since this seems to be fixed now.
