### ISSUE TITLE
GitHub Container Registry as a compatible registry

### ISSUE THREAD

**Issue by clarkbw** [cnabio/cnab.io#44]
👋  Hello!

GitHub Container Registry ghcr.io is an OCI compatible container registry that could be listed on https://cnab.io/registries/

In the next quarter we're going to migrate all of the GitHub Packages (Docker) users over which will complete the GA transition.

Thanks,
~ Bryan

**Comment by carolynvs** [comment]
Great! I will try it out and update the page.
